### ISSUE TITLE
Indentar código e PSR'S

### ISSUE THREAD

**Issue by amskywalker** [Ronivaldo01/Sistema_Crud#1]
Tenta indentar um pouco o código, se você usa o VSCode, aperta Shift+Alt+F e quando tu tem arquivos apenas com php, é recomendável não usar usar a tag de fechamento ?>

Vale a leitura:
https://www.php-fig.org/psr/

**Comment by Ronivaldo01** [comment]
Boa tarde obrigado pela dica ... a verdade é que coloquei o código lá mais por está mesmo ... eu conheço as normas procedimentos nomenclatura ,,, estava sem internet ... foi praticamente impossível ter subido o teste para o github ... estava sem internet e cheguei em casa pelas 23:00 da noite vindo de entrevista de emprego, eu vou terminar esse projeto mais pra frente ... pois me pediram outros desafios e oportunidade está difícil hoje em dia ... se você não conhece ninguém para te indicar fica praticamente impossível ... mas entrego o meu futuro na mão de Deus ... vou colocar um projeto em react lá no git também, para começar a usar o git novamente, pois eu só usava o gitlab em projetos das empresas que atuei. 
    Em quinta-feira, 1 de outubro de 2020 14:11:38 BRT, Adailton Moura <notifications@github.com> escreveu:  
 
 


Tenta indentar um pouco o código, se você usa o VSCode, aperta Shift+Alt+F e quando tu tem arquivos apenas com php, é recomendável não usar usar a tag de fechamento ?>

Vale a leitura:
https://www.php-fig.org/psr/

**Comment by amskywalker** [comment]
Compreendo, o github é muito bom, use os recursos dele ao máximo.
Se tiver alguma dúvida, pode me contatar, as minhas redes sociais estão no meu perfil,  boa sorte.
